### ISSUE TITLE
What about setting keys?

### ISSUE THREAD

**Issue by PhilipMay** [telekom/ml-cloud-tools#4]
Do we have to add the possibility to set keys?
ACCESS_KEY or SECRET_KEY or something like that?
@twolffpiggott

**Comment by PhilipMay** [comment]
I think credentials are set in `~/.aws/credentials` or as Environment variables

**Comment by twolffpiggott** [comment]
I think the responsibility for key setting should reside with the client, since it is relevant to their AWS account in general and not just this package.

If we want to, we can wrap the exceptions raised by boto3 to give more informative messages around credential setting.

**Comment by PhilipMay** [comment]
Ok. So closing this. Thanks @twolffpiggott
